=== Segvek/TaskManager/WebService/src/main/webapp/schems/APIRequest.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="request">
        <xs:complexType>
            <xs:all>
                <xs:element name="registration" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для регистрации нового пользователя
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name"/>
                            <xs:element name="mail"/>
                            <xs:element name="hashPass"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="authorization"  minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для авторизации пользователя 
                            структура ответа описана в документе APIResponce.xsd с аналогичным именем
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/> <!--логин пользователя-->
                            <xs:element name="hashPass" type="xs:string"/> <!--зашифрованый пароль md5-->
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="createGoal" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для создания цели авторизированым пользователем
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sessionId"/>
                            <xs:element name="name"/>
                            <xs:element name="anotation"/>
                            <xs:element name="beginDate"/>
                            <xs:element name="endDate"/>
                            <xs:element name="plan">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="number"/>
                                                    <xs:element name="name"/>
                                                    <xs:element name="beginDate"/> 
                                                    <xs:element name="endDate"/>
                                                    <xs:element minOccurs="0" name="idAcount"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
<!--                <xs:element name="createPlanToDay" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для создания цели авторизированым пользователем
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date"/>
                            <xs:element name="plan">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="number"/>
                                                    <xs:element name="name"/>
                                                    <xs:element name="status">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Begin"/>
                                                                <xs:enumeration value="Processed"/>
                                                                <xs:enumeration value="End"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element minOccurs="0" name="globalPlan">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="numberGoal"/>
                                                                <xs:element name="numberItemPlan"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element minOccurs="0" name="notice"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>-->
                <xs:element name="confirmation" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для подтверждения регистрации нового пользователя
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sessionId"/>
                            <xs:element name="key"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="closeSession" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для завершения сесии пользователя который хочет выйти из акаунта
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sessionId"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="userState" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для Отображения текущего состояния пользовательского акаунта
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sessionId"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="userGoals" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для Отображения списка пользовательских целей 
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sessionId"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="palnToDay" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для Отображения плана на сегодня
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sessionId"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                 <xs:element name="goalInfo" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Данная функция предназначена для получение информации о цели
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sessionId"/>
                            <xs:element name="golaID"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!--сюда добавлять новые функции-->
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Segvek/TaskManager/WebService/src/main/webapp/schems/testRequest.xml
<?xml version="1.0" encoding="UTF-8"?>

<request
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='APIRequest.xsd'>
    <!--Пример запроса на регистрацию-->
    <registration>
        <name>YuriPanasenco</name>
        <mail>Panasenco@outlook.com</mail>
        <hashPass>12345</hashPass>
    </registration>
    
    <!--Пример запроса на авторизацию-->
    <authorization>
        <name>ebtb</name>
        <hashPass>sdfvrf</hashPass>
    </authorization>
        
    <!--пример запроса на создание цели-->
    <createGoal>
        <sessionId>tnlekmgregreko54ymn6oyh5k4my</sessionId>
        <name>Название цели</name>
        <anotation>Краткое описание цели</anotation>
        <beginDate>07.09.2016</beginDate>
        <endDate>01.07.2018</endDate>
        <plan>
            <item>
                <number>1</number>
                <name>Получить высшее образование (Уровень бакалавр)</name>
                <beginDate>01.09.2016</beginDate>
                <endDate>01.07.2018</endDate>
            </item>
            <item>
                <number>2</number>
                <name>Накопить 5 тыс. доларов</name>
                <beginDate>01.09.2016</beginDate>
                <endDate>01.07.2018</endDate>
                <idAcount>4</idAcount>
            </item>
        </plan>
    </createGoal>

    <!--пример запроса на закрытие сесии-->
    <closeSession>
        <sessionId>tnlekmgregreko54ymn6oyh5k4my</sessionId>
    </closeSession>
    
    <!--пример запроса на получение информации о пользователе-->
    <userState>
        <sessionId>tnlekmgregreko54ymn6oyh5k4my</sessionId>
    </userState>
    
    <!--пример запроса на получение списка пользовательских целей-->
    <userGoals>
        <sessionId>tnlekmgregreko54ymn6oyh5k4my</sessionId>
    </userGoals>
    
    <!--пример запроса на получение отчета по конкретной цели-->
    <goalInfo>
        <sessionId>tnlekmgregreko54ymn6oyh5k4my</sessionId>
        <golaID>234</golaID>
    </goalInfo>
    
    
    
    
    
    <!--Пример запроса для подтверждения регистрации-->
    <confirmation>
        <sessionId>tnlekmgregreko54ymn6oyh5k4my</sessionId>
        <key>uijonuhibjonot6f5ft7</key>
    </confirmation>
    <!--пример запроса на содание плана на завтра-->
<!--    <createPlanToDay>
        <date>04.09.2016</date>дата на когда создается план
        <plan>
            <item>
                <number>1</number>
                <name>Задание 1</name>
                <status>Begin</status>
                <globalPlan>
                    <numberGoal>1</numberGoal>
                    <numberItemPlan>2</numberItemPlan>
                </globalPlan>
            </item>
            <item>
                <number>2</number>
                <name>Задание 2</name>
                <status>Begin</status>
            </item>
        </plan>
    </createPlanToDay>-->
    
    
    
    <palnToDay>
        <sessionId>tnlekmgregreko54ymn6oyh5k4my</sessionId>
    </palnToDay>
    
</request>
